name: test

on:
  - push:
    tags:
      - v*.*.*
  - pull_request

jobs:
  build_osx:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: echo ${{ github.sha }} > Newfile.txt
    - name: Release test
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Newfile.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
